import { createElement, forwardRef, useCallback, useState } from "react";
import { cn } from "../../../utils/cn";
import "./AnchorHeading.css";

export type AnchorHeadingLevel = 1 | 2 | 3 | 4 | 5 | 6;

/** Slugify text content into a URL-safe id. */
function slugify(value: string): string {
  return value
    .trim()
    .toLowerCase()
    .replace(/[^\w\s-]/g, "")
    .replace(/[\s_]+/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-+|-+$/g, "");
}

export interface AnchorHeadingProps
  extends React.HTMLAttributes<HTMLHeadingElement> {
  /** Semantic heading level; renders the matching `h1`–`h6`. Defaults to `2`. */
  level?: AnchorHeadingLevel;
  /**
   * Explicit id for the heading and its anchor target. When omitted, an id is
   * generated by slugifying the string children.
   */
  id?: string;
  /** Accessible label for the anchor link. Defaults to `"Link to this section"`. */
  anchorLabel?: string;
}

/**
 * A heading with a hover-revealed `#` anchor link that targets its own id and
 * copies the resulting URL hash to the clipboard on click. Built for docs.
 */
export const AnchorHeading = forwardRef<HTMLHeadingElement, AnchorHeadingProps>(
  function AnchorHeading(
    {
      level = 2,
      id,
      anchorLabel = "Link to this section",
      className,
      children,
      ...rest
    },
    ref
  ) {
    const [copied, setCopied] = useState(false);

    const resolvedId =
      id ?? (typeof children === "string" ? slugify(children) : undefined);

    const handleCopy = useCallback(() => {
      if (!resolvedId) return;
      if (typeof window === "undefined") return;

      const url = `${window.location.origin}${window.location.pathname}${window.location.search}#${resolvedId}`;

      const markCopied = () => {
        setCopied(true);
        window.setTimeout(() => setCopied(false), 1500);
      };

      if (navigator?.clipboard?.writeText) {
        navigator.clipboard.writeText(url).then(markCopied).catch(() => {
          /* clipboard denied — anchor navigation still works */
        });
      }
    }, [resolvedId]);

    return createElement(
      `h${level}`,
      {
        ref,
        id: resolvedId,
        className: cn("nova-anchor-heading", className),
        ...rest,
      },
      <>
        <span className="nova-anchor-heading__text">{children}</span>
        {resolvedId ? (
          <a
            href={`#${resolvedId}`}
            className="nova-anchor-heading__anchor nova-focusable"
            aria-label={anchorLabel}
            data-copied={copied || undefined}
            onClick={handleCopy}
          >
            <span aria-hidden="true">#</span>
          </a>
        ) : null}
      </>
    );
  }
);
