// Nova UI — landing-page catalog generator.
//
// Reads the machine-readable manifest (docs/components.json, produced by
// generate-manifest.mjs) and emits a compact, display-oriented catalog for the
// marketing/overview site: demo/catalog.generated.ts.
//
// Keeping this separate from the 270 KB manifest means the site bundles only
// category labels, icons and component *names* — never the full descriptions.
// Counts and name lists stay auto-accurate; labels/icons/order live here.
//
// ESM, Node built-ins only. Deterministic (no timestamps).

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");
const MANIFEST = path.join(ROOT, "docs", "components.json");
const OUT = path.join(ROOT, "demo", "catalog.generated.ts");

// Display metadata per category folder. `signature` marks the distinctive,
// motion-driven Aceternity/Magic-UI-flavour categories. `order` controls the
// overview grid: signature categories lead, foundational ones follow.
const META = {
  texteffects:    { label: "Text Effects",        icon: "✶", signature: true,  order: 1 },
  fx:             { label: "FX & Backgrounds",     icon: "◍", signature: true,  order: 2 },
  flair:          { label: "Flair",                icon: "✦", signature: true,  order: 3 },
  showcase:       { label: "Showcase",             icon: "▦", signature: true,  order: 4 },
  loaders:        { label: "Loaders",              icon: "◌", signature: true,  order: 5 },
  cursor:         { label: "Cursor FX",            icon: "➤", signature: true,  order: 6 },
  threed:         { label: "3D & Perspective",     icon: "◈", signature: true,  order: 7 },
  devices:        { label: "Device Mockups",       icon: "▢", signature: true,  order: 8 },
  patterns:       { label: "Patterns & Dividers",  icon: "〜", signature: true,  order: 9 },
  gamification:   { label: "Gamification",         icon: "★", signature: true,  order: 10 },
  inputs:         { label: "Inputs & Forms",       icon: "⌨", signature: false, order: 11 },
  layout:         { label: "Layout",               icon: "▤", signature: false, order: 12 },
  navigation:     { label: "Navigation",           icon: "⊳", signature: false, order: 13 },
  feedback:       { label: "Feedback",             icon: "◉", signature: false, order: 14 },
  "data-display": { label: "Data Display",         icon: "▥", signature: false, order: 15 },
  charts:         { label: "Charts",               icon: "◔", signature: false, order: 16 },
  typography:     { label: "Typography",           icon: "Tt", signature: false, order: 17 },
  overlay:        { label: "Overlay",              icon: "▣", signature: false, order: 18 },
  disclosure:     { label: "Disclosure",           icon: "▾", signature: false, order: 19 },
  media:          { label: "Media",                icon: "▶", signature: false, order: 20 },
  motion:         { label: "Motion",               icon: "↻", signature: false, order: 21 },
  blocks:         { label: "Blocks",               icon: "◰", signature: false, order: 22 },
  commerce:       { label: "Commerce",             icon: "⛁", signature: false, order: 23 },
  chat:           { label: "Chat & Messaging",     icon: "✉", signature: false, order: 24 },
  scheduling:     { label: "Scheduling",           icon: "◷", signature: false, order: 25 },
  dnd:            { label: "Drag & Drop",          icon: "⤢", signature: false, order: 26 },
  templates:      { label: "Page Templates",       icon: "❏", signature: false, order: 27 },
  utility:        { label: "Utility & Hooks",      icon: "⚙", signature: false, order: 28 },
};

const manifest = JSON.parse(fs.readFileSync(MANIFEST, "utf8"));

const categories = manifest.categories
  .map((cat) => {
    const meta = META[cat.name] ?? {
      label: cat.name,
      icon: "◆",
      signature: false,
      order: 999,
    };
    // Component display name = the folder name (== primary export).
    const components = cat.components.map((c) => c.name);
    return {
      key: cat.name,
      label: meta.label,
      icon: meta.icon,
      signature: meta.signature,
      order: meta.order,
      count: cat.count,
      components,
    };
  })
  .sort((a, b) => a.order - b.order)
  // Drop the sort-only `order` key so the literal matches CatalogCategory
  // exactly (TS excess-property check on the typed array).
  .map(({ order, ...rest }) => rest);

const banner =
  "// AUTO-GENERATED by scripts/generate-catalog.mjs — do not edit by hand.\n" +
  "// Run `npm run docs:catalog` (or `npm run docs`) to regenerate.\n\n";

const body =
  banner +
  "export interface CatalogCategory {\n" +
  "  /** Source folder name, e.g. `texteffects`. */\n" +
  "  key: string;\n" +
  "  /** Human label for the overview grid. */\n" +
  "  label: string;\n" +
  "  /** Single-glyph icon. */\n" +
  "  icon: string;\n" +
  "  /** Distinctive, motion-driven “signature” category. */\n" +
  "  signature: boolean;\n" +
  "  /** Number of components in the category. */\n" +
  "  count: number;\n" +
  "  /** Component names (== primary exports), source order. */\n" +
  "  components: string[];\n" +
  "}\n\n" +
  `export const TOTAL_COMPONENTS = ${manifest.totalComponents};\n` +
  `export const TOTAL_CATEGORIES = ${manifest.totalCategories};\n` +
  `export const SIGNATURE_COUNT = ${categories.filter((c) => c.signature).length};\n\n` +
  "export const CATALOG: CatalogCategory[] = " +
  JSON.stringify(categories, null, 2) +
  ";\n";

fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(OUT, body, "utf8");

console.log("Nova UI catalog generated.");
console.log(`  Categories: ${categories.length}`);
console.log(`  Components: ${manifest.totalComponents}`);
console.log(`  -> ${path.relative(ROOT, OUT)}`);
